# 긍부정으로 만들어야 할것
- 여성남성 전체 긍부정 도넛 ======== 여성남성전체읽기, 긍부정도넛 해봐서 합치기만 하면됨
- 카테고리별로 긍부정 스택바 =========== 카테고리별 긍부정은 지은이한테 부탁. 스택바 안해봄
- 긍부정 연도별 꺾은선 =============여성남성 모든 파일로 완성


### 저장한 파일 ( 전부 다 연도별 ) 
- sent_w_count.csv : 여자 긍부정 카운트
- sent_m_count.csv : 남자 긍부정 카운트
- wtotal_count.csv : 여자 데이터 카운트
- mtotal_count.csv : 남자 데이터 카운트

In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pygal
import glob

In [2]:
dfsent = pd.read_excel(r'C:\Users\user\Desktop\SENT#4_2000_03_남성.xlsx', encoding='CP949', index_col=0)

In [3]:
dfsent

,title,source,date,url,text,sentiment
0,"현대해상, 80세까지 보장보험 판매",한국경제,20000301,https://news.naver.com/main/read.nhn?mode=LSD&...,현대해상은 세까지 보장해주는 새천년 남성 여성 건강보험 을 개발해 2일부터 판매한다...,0
1,"'남자만 병역의무' 헌법소원, 2건 모두 각하",한국경제,20000301,https://news.naver.com/main/read.nhn?mode=LSD&...,남자만 병역의무를 지도록 규정한 병역법 조항에 대해 제기한 헌법소원 2건이 모두 각...,0
2,"[쇼핑] (외식 나들이) 삐에뜨로, 남성정장 무료증정",한국경제,20000302,https://news.naver.com/main/read.nhn?mode=LSD&...,삐에뜨로는 입학시즌을 맞아 오는 5일까지 현대백화점과 공동으로 매장을방문한 고객을 ...,0
3,[알림] 소설 '불감시대' 6일부터 연재,한국경제,20000302,https://news.naver.com/main/read.nhn?mode=LSD&...,한국경제신문은 오는 6일자부터 중진 작가 홍상화씨의 장편 소설 불감시대 를 연재합니...,1
4,[코스닥면톱] '덩치' 작은종목 장세주도,한국경제,20000302,https://news.naver.com/main/read.nhn?mode=LSD&...,자본금 규모가 작은 종목을 잡아라 업종에 상관없이 자본금 규모가 작은 기업의 주가...,1
...,...,...,...,...,...,...
59,[제3회 광주비엔날레] '人+間' .. 아시아 작가 큰 관심,한국경제,20000330,https://news.naver.com/main/read.nhn?mode=LSD&...,인 간 아시아 최대의 미술축제로 자리잡은 광주 비엔날레는 올해 3회 주제를 인간 ...,1
60,[제3회 광주비엔날레] 이란 작가 쉬린 네샤트의 '무제'..대상 수상작,한국경제,20000330,https://news.naver.com/main/read.nhn?mode=LSD&...,양쪽 벽면에 투사된 흑백 화면에 카운트다운이 흐른다.\n왼쪽벽에 막막한 사막이 펼쳐...,1
61,"명진타스코, 발기부전 개선식품 ""웨이거"" 판매",한국경제,20000330,https://news.naver.com/main/read.nhn?mode=LSD&...,명진타스코는 산수유에서 추출한 발기부전 개선식품인 웨이거 를 수입 판매하고 있다.\...,0
62,미국 여성중장 '성희롱당했다' 고발,한국경제,20000331,https://news.naver.com/main/read.nhn?mode=LSD&...,미국의 별 셋짜리 여성장군이 동료 남성장군으로부터 성희롱을 당했다고 해서화제다.\n...,0
63,[여론광장] 시내버스 운전석 뒷자리 '삽/빗자루 두지 말았으면',한국경제,20000331,https://news.naver.com/main/read.nhn?mode=LSD&...,매일 대중교통을 이용해 출근한다.\n주로 시내버스를 이용하는데 해가 가도 개선되지 ...,0

In [6]:
#https://stackoverflow.com/questions/48539714/creating-pygal-bar-chart-from-pandas-series-value-counts
# 마우스를 올려야 수치가 보임
# 

# series = dfsent.sentiment.value_counts().sort_index()

# chart = pygal.Pie(inner_radius=.4)
# chart.title = '긍부정 분포'
# chart.add('긍정' , series.values[0])
# chart.add('부정' , series.values[1])
# chart.render()

# chart.render_to_file('sentdonut.svg')

## 모든파일(여자+남자) 년도별로 긍부정 count 데이터프레임 만들기

In [3]:
yearlist = []
yearlist.append([i for i in range(2000,2020)])
yearlist = list(map(str, yearlist[0]))
df_year = pd.DataFrame(0, index=range(0,2),columns=list(map(str,range(2000,2020))))
df_year

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [6]:
from collections import Counter
df_name = glob.glob('../xlsx_data/#4_result/')
dict_catcount = { 0 : 0, 1 : 0, 2 : 0, 3 : 0, 4 : 0, 5 : 0, 6 : 0}

for i, d in enumerate(df_name):
    for f in glob.glob(d+"/*/*.xlsx"):
        df = pd.read_excel(f)
        for i in yearlist:
            if i in f:
                print(i)
                try:
                    temp = df.sentiment.value_counts().sort_index()
                    df_year[i] += temp
                except:
                    pass
#         dict_cat = dfcat.category.value_counts().sort_index().to_dict()
#         dict_catcount = Counter(dict_catcount) + Counter(dict_cat)

2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2002
2002
2002
2002
2002
2002
2002
2002
2002
2002
2002
2002
2003
2003
2003
2003
2003
2003
2003
2003
2003
2003
2003
2003
2004
2004
2004
2004
2004
2004
2004
2004
2004
2004
2004
2004
2005
2005
2005
2005
2005
2005
2005
2005
2005
2005
2005

KeyboardInterrupt:

In [7]:
df_year

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,1332,2041,3188,5059,9496,10902,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1521,2288,3346,4210,7589,10714,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## 긍부정별로 꺾은선 그래프 그리기

In [33]:
chart = pygal.Line()
chart.x_labels = yearlist
chart.add('긍정', df_year.loc[0])
chart.add('부정', df_year.loc[1])
chart.render_to_file('your_path_to_file.svg')

# 여자 긍부정 꺾은선 그래프

In [2]:
wdf_year = pd.DataFrame(0, index=range(0,2),columns=list(map(str,range(2000,2020))))
wdf_year

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
from collections import Counter
df_name = glob.glob('../xlsx_data/#4_result/#4_여성/')
cnt = 0
wdf_year = pd.DataFrame(0, index=range(0,2),columns=list(map(str,range(2000,2020))))
for i, d in enumerate(df_name):
        for f in glob.glob(d+"/*.xlsx"):
            year = f[32:36]
            print(year)
            cnt += 1
            df = pd.read_excel(f)
            print(f)
            try:
                temp = df.sentiment.value_counts().sort_index()
                wdf_year[year] += temp                    
            except:
                print('empty file')
                pass
            if cnt%24 == 0:
                print('================== 여기까지 :', year, '년 ==================')

2000
../xlsx_data/#4_result/#4_여성\#4_2000_01_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_01_여자+-여성.xlsx
empty file
2000
../xlsx_data/#4_result/#4_여성\#4_2000_02_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_02_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_03_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_03_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_04_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_04_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_05_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_05_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_06_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_06_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_07_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_07_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_08_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_08_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_09_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_09_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_10_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_10_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_11_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_11_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_12_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_12_여자+-여성.xlsx
================== 여기까지 : 2000 년 ==================
2001
../xlsx_data/#4_result/#4_여성\#4_2001_01_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_01_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_02_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_02_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_03_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_03_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_04_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_04_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_05_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_05_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_06_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_06_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_07_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_07_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_08_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_08_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_09_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_09_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_10_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_10_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_11_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_11_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_12_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_12_여자+-여성.xlsx
================== 여기까지 : 2001 년 ==================
2002
../xlsx_data/#4_result/#4_여성\#4_2002_01_여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_01_여자+-여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_02_여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_02_여자+-여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_03_여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_03_여자+-여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_04_여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_04_여자+-여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_05_여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_05_여자+-여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_06_여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_06_여자+-여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_07_여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_07_여자+-여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_08_여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_08_여자+-여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_09_여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_09_여자+-여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_10_여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_10_여자+-여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_11_여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_11_여자+-여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_12_여성.xlsx
2002
../xlsx_data/#4_result/#4_여성\#4_2002_12_여자+-여성.xlsx
================== 여기까지 : 2002 년 ==================
2003
../xlsx_data/#4_result/#4_여성\#4_2003_01_여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_01_여자+-여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_02_여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_02_여자+-여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_03_여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_03_여자+-여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_04_여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_04_여자+-여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_05_여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_05_여자+-여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_06_여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_06_여자+-여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_07_여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_07_여자+-여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_08_여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_08_여자+-여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_09_여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_09_여자+-여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_10_여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_10_여자+-여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_11_여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_11_여자+-여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_12_여성.xlsx
2003
../xlsx_data/#4_result/#4_여성\#4_2003_12_여자+-여성.xlsx
================== 여기까지 : 2003 년 ==================
2004
../xlsx_data/#4_result/#4_여성\#4_2004_01_여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_01_여자+-여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_02_여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_02_여자+-여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_03_여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_03_여자+-여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_04_여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_04_여자+-여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_05_여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_05_여자+-여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_06_여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_06_여자+-여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_07_여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_07_여자+-여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_08_여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_08_여자+-여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_09_여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_09_여자+-여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_10_여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_10_여자+-여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_11_여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_11_여자+-여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_12_여성.xlsx
2004
../xlsx_data/#4_result/#4_여성\#4_2004_12_여자+-여성.xlsx
================== 여기까지 : 2004 년 ==================
2005
../xlsx_data/#4_result/#4_여성\#4_2005_01_여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_01_여자+-여성.xlsx
empty file
2005
../xlsx_data/#4_result/#4_여성\#4_2005_02_여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_02_여자+-여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_03_여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_03_여자+-여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_04_여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_04_여자+-여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_05_여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_05_여자+-여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_06_여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_06_여자+-여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_07_여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_07_여자+-여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_08_여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_08_여자+-여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_09_여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_09_여자+-여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_10_여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_10_여자+-여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_11_여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_11_여자+-여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_12_여성.xlsx
2005
../xlsx_data/#4_result/#4_여성\#4_2005_12_여자+-여성.xlsx
================== 여기까지 : 2005 년 ==================
2006

../xlsx_data/#4_result/#4_여성\#4_2006_01_여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_01_여자+-여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_02_여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_02_여자+-여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_03_여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_03_여자+-여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_04_여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_04_여자+-여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_05_여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_05_여자+-여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_06_여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_06_여자+-여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_07_여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_07_여자+-여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_08_여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_08_여자+-여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_09_여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_09_여자+-여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_10_여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_10_여자+-여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_11_여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_11_여자+-여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_12_여성.xlsx
2006
../xlsx_data/#4_result/#4_여성\#4_2006_12_여자+-여성.xlsx
================== 여기까지 : 2006 년 ==================
2007
../xlsx_data/#4_result/#4_여성\#4_2007_01_여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_01_여자+-여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_02_여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_02_여자+-여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_03_여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_03_여자+-여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_04_여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_04_여자+-여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_05_여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_05_여자+-여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_06_여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_06_여자+-여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_07_여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_07_여자+-여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_08_여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_08_여자+-여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_09_여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_09_여자+-여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_10_여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_10_여자+-여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_11_여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_11_여자+-여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_12_여성.xlsx
2007
../xlsx_data/#4_result/#4_여성\#4_2007_12_여자+-여성.xlsx
================== 여기까지 : 2007 년 ==================
2008
../xlsx_data/#4_result/#4_여성\#4_2008_01_여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_01_여자+-여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_02_여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_02_여자+-여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_03_여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_03_여자+-여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_04_여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_04_여자+-여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_05_여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_05_여자+-여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_06_여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_06_여자+-여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_07_여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_07_여자+-여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_08_여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_08_여자+-여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_09_여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_09_여자+-여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_10_여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_10_여자+-여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_11_여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_11_여자+-여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_12_여성.xlsx
2008
../xlsx_data/#4_result/#4_여성\#4_2008_12_여자+-여성.xlsx
================== 여기까지 : 2008 년 ==================
2009
../xlsx_data/#4_result/#4_여성\#4_2009_01_여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_01_여자+-여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_02_여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_02_여자+-여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_03_여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_03_여자+-여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_04_여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_04_여자+-여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_05_여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_05_여자+-여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_06_여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_06_여자+-여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_07_여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_07_여자+-여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_08_여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_08_여자+-여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_09_여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_09_여자+-여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_10_여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_10_여자+-여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_11_여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_11_여자+-여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_12_여성.xlsx
2009
../xlsx_data/#4_result/#4_여성\#4_2009_12_여자+-여성.xlsx
================== 여기까지 : 2009 년 ==================
2010
../xlsx_data/#4_result/#4_여성\#4_2010_01_여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_01_여자+-여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_02_여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_02_여자+-여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_03_여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_03_여자+-여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_04_여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_04_여자+-여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_05_여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_05_여자+-여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_06_여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_06_여자+-여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_07_여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_07_여자+-여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_08_여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_08_여자+-여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_09_여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_09_여자+-여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_10_여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_10_여자+-여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_11_여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_11_여자+-여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_12_여성.xlsx
2010
../xlsx_data/#4_result/#4_여성\#4_2010_12_여자+-여성.xlsx
================== 여기까지 : 2010 년 ==================
2011
../xlsx_data/#4_result/#4_여성\#4_2011_01_여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_01_여자+-여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_02_여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_02_여자+-여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_03_여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_03_여자+-여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_04_여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_04_여자+-여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_05_여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_05_여자+-여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_06_여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_06_여자+-여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_07_여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_07_여자+-여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_08_여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_08_여자+-여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_09_여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_09_여자+-여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_10_여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_10_여자+-여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_11_여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_11_여자+-여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_12_여성.xlsx
2011
../xlsx_data/#4_result/#4_여성\#4_2011_12_여자+-여성.xlsx
================== 여기까지 : 2011 년 ==================
2012

../xlsx_data/#4_result/#4_여성\#4_2012_01_여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_01_여자+-여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_02_여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_02_여자+-여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_03_여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_03_여자+-여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_04_여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_04_여자+-여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_05_여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_05_여자+-여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_06_여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_06_여자+-여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_07_여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_07_여자+-여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_08_여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_08_여자+-여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_09_여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_09_여자+-여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_10_여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_10_여자+-여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_11_여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_11_여자+-여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_12_여성.xlsx
2012
../xlsx_data/#4_result/#4_여성\#4_2012_12_여자+-여성.xlsx
================== 여기까지 : 2012 년 ==================
2013
../xlsx_data/#4_result/#4_여성\#4_2013_01_여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_01_여자+-여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_02_여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_02_여자+-여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_03_여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_03_여자+-여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_04_여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_04_여자+-여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_05_여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_05_여자+-여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_06_여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_06_여자+-여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_07_여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_07_여자+-여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_08_여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_08_여자+-여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_09_여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_09_여자+-여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_10_여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_10_여자+-여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_11_여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_11_여자+-여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_12_여성.xlsx
2013
../xlsx_data/#4_result/#4_여성\#4_2013_12_여자+-여성.xlsx
================== 여기까지 : 2013 년 ==================
2014
../xlsx_data/#4_result/#4_여성\#4_2014_01_여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_01_여자+-여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_02_여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_02_여자+-여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_03_여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_03_여자+-여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_04_여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_04_여자+-여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_05_여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_05_여자+-여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_06_여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_06_여자+-여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_07_여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_07_여자+-여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_08_여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_08_여자+-여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_09_여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_09_여자+-여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_10_여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_10_여자+-여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_11_여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_11_여자+-여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_12_여성.xlsx
2014
../xlsx_data/#4_result/#4_여성\#4_2014_12_여자+-여성.xlsx
================== 여기까지 : 2014 년 ==================
2015
../xlsx_data/#4_result/#4_여성\#4_2015_01_여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_01_여자+-여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_02_여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_02_여자+-여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_03_여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_03_여자+-여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_04_여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_04_여자+-여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_05_여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_05_여자+-여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_06_여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_06_여자+-여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_07_여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_07_여자+-여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_08_여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_08_여자+-여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_09_여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_09_여자+-여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_10_여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_10_여자+-여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_11_여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_11_여자+-여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_12_여성.xlsx
2015
../xlsx_data/#4_result/#4_여성\#4_2015_12_여자+-여성.xlsx
================== 여기까지 : 2015 년 ==================
2016
../xlsx_data/#4_result/#4_여성\#4_2016_01_여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_01_여자+-여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_02_여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_02_여자+-여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_03_여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_03_여자+-여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_04_여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_04_여자+-여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_05_여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_05_여자+-여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_06_여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_06_여자+-여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_07_여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_07_여자+-여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_08_여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_08_여자+-여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_09_여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_09_여자+-여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_10_여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_10_여자+-여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_11_여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_11_여자+-여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_12_여성.xlsx
2016
../xlsx_data/#4_result/#4_여성\#4_2016_12_여자+-여성.xlsx
================== 여기까지 : 2016 년 ==================
2017
../xlsx_data/#4_result/#4_여성\#4_2017_01_여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_01_여자+-여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_02_여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_02_여자+-여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_03_여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_03_여자+-여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_04_여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_04_여자+-여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_05_여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_05_여자+-여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_06_여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_06_여자+-여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_07_여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_07_여자+-여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_08_여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_08_여자+-여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_09_여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_09_여자+-여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_10_여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_10_여자+-여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_11_여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_11_여자+-여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_12_여성.xlsx
2017
../xlsx_data/#4_result/#4_여성\#4_2017_12_여자+-여성.xlsx
================== 여기까지 : 2017 년 ==================
2018

../xlsx_data/#4_result/#4_여성\#4_2018_01_여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_01_여자+-여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_02_여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_02_여자+-여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_03_여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_03_여자+-여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_04_여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_04_여자+-여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_05_여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_05_여자+-여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_06_여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_06_여자+-여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_07_여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_07_여자+-여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_08_여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_08_여자+-여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_09_여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_09_여자+-여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_10_여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_10_여자+-여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_11_여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_11_여자+-여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_12_여성.xlsx
2018
../xlsx_data/#4_result/#4_여성\#4_2018_12_여자+-여성.xlsx
================== 여기까지 : 2018 년 ==================
2019
../xlsx_data/#4_result/#4_여성\#4_2019_01_여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_01_여자+-여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_02_여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_02_여자+-여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_03_여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_03_여자+-여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_04_여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_04_여자+-여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_05_여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_05_여자+-여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_06_여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_06_여자+-여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_07_여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_07_여자+-여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_08_여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_08_여자+-여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_09_여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_09_여자+-여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_10_여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_10_여자+-여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_11_여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_11_여자+-여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_12_여성.xlsx
2019
../xlsx_data/#4_result/#4_여성\#4_2019_12_여자+-여성.xlsx
================== 여기까지 : 2019 년 ==================

In [8]:
wdf_year

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,6219,8852,16020,22677,42207,50262,67439,89563,98410,124304,118355,132364,164125,218280,276896,364106,325017,291384,328168,327789
1,5742,8878,13369,16875,32238,47851,67444,88238,102850,150155,154676,183614,196755,278833,374800,446124,332980,309685,318375,281008

In [96]:
chart = pygal.Line()
chart.x_labels = wdf_year.columns
chart.add('긍정', wdf_year.loc[0])
chart.add('부정', wdf_year.loc[1])
chart.render_to_file('w_sentiment_line.svg')

In [97]:
wdf_year.to_csv('sent_w_count.csv')

# 남자 긍부정 꺾은선 그래프

In [4]:
mdf_year = pd.DataFrame(0, index=range(0,2),columns=list(map(str,range(2000,2020))))
mdf_year

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [5]:
from collections import Counter
df_name = glob.glob('../xlsx_data/#4_result/#4_남성/')
cnt = 0
mdf_year = pd.DataFrame(0, index=range(0,2),columns=list(map(str,range(2000,2020))))
for i, d in enumerate(df_name):
        for f in glob.glob(d+"/*.xlsx"):
            year = f[32:36]
            print(year)
            cnt += 1
            df = pd.read_excel(f)
            print(f)
            try:
                temp = df.sentiment.value_counts().sort_index()
                mdf_year[year] += temp                    
            except:
                print('empty file')
                pass
            if cnt%24 == 0:
                print('================== 여기까지 :', year, '년 ==================')

2000
../xlsx_data/#4_result/#4_남성\#4_2000_01_남성.xlsx
empty file
2000
../xlsx_data/#4_result/#4_남성\#4_2000_01_남자+-남성.xlsx
empty file
2000
../xlsx_data/#4_result/#4_남성\#4_2000_02_남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_02_남자+-남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_03_남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_03_남자+-남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_04_남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_04_남자+-남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_05_남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_05_남자+-남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_06_남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_06_남자+-남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_07_남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_07_남자+-남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_08_남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_08_남자+-남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_09_남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_09_남자+-남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_10_남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_10_남자+-남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_11_남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_11_남자+-남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_12_남성.xlsx
2000
../xlsx_data/#4_result/#4_남성\#4_2000_12_남자+-남성.xlsx
================== 여기까지 : 2000 년 ==================
2001
../xlsx_data/#4_result/#4_남성\#4_2001_01_남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_01_남자+-남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_02_남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_02_남자+-남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_03_남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_03_남자+-남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_04_남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_04_남자+-남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_05_남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_05_남자+-남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_06_남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_06_남자+-남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_07_남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_07_남자+-남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_08_남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_08_남자+-남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_09_남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_09_남자+-남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_10_남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_10_남자+-남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_11_남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_11_남자+-남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_12_남성.xlsx
2001
../xlsx_data/#4_result/#4_남성\#4_2001_12_남자+-남성.xlsx
================== 여기까지 : 2001 년 ==================
2002
../xlsx_data/#4_result/#4_남성\#4_2002_01_남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_01_남자+-남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_02_남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_02_남자+-남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_03_남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_03_남자+-남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_04_남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_04_남자+-남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_05_남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_05_남자+-남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_06_남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_06_남자+-남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_07_남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_07_남자+-남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_08_남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_08_남자+-남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_09_남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_09_남자+-남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_10_남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_10_남자+-남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_11_남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_11_남자+-남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_12_남성.xlsx
2002
../xlsx_data/#4_result/#4_남성\#4_2002_12_남자+-남성.xlsx
================== 여기까지 : 2002 년 ==================
2003
../xlsx_data/#4_result/#4_남성\#4_2003_01_남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_01_남자+-남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_02_남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_02_남자+-남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_03_남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_03_남자+-남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_04_남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_04_남자+-남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_05_남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_05_남자+-남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_06_남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_06_남자+-남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_07_남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_07_남자+-남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_08_남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_08_남자+-남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_09_남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_09_남자+-남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_10_남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_10_남자+-남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_11_남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_11_남자+-남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_12_남성.xlsx
2003
../xlsx_data/#4_result/#4_남성\#4_2003_12_남자+-남성.xlsx
================== 여기까지 : 2003 년 ==================
2004
../xlsx_data/#4_result/#4_남성\#4_2004_01_남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_01_남자+-남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_02_남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_02_남자+-남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_03_남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_03_남자+-남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_04_남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_04_남자+-남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_05_남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_05_남자+-남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_06_남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_06_남자+-남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_07_남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_07_남자+-남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_08_남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_08_남자+-남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_09_남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_09_남자+-남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_10_남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_10_남자+-남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_11_남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_11_남자+-남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_12_남성.xlsx
2004
../xlsx_data/#4_result/#4_남성\#4_2004_12_남자+-남성.xlsx
================== 여기까지 : 2004 년 ==================
2005
../xlsx_data/#4_result/#4_남성\#4_2005_01_남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_01_남자+-남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_02_남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_02_남자+-남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_03_남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_03_남자+-남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_04_남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_04_남자+-남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_05_남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_05_남자+-남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_06_남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_06_남자+-남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_07_남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_07_남자+-남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_08_남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_08_남자+-남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_09_남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_09_남자+-남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_10_남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_10_남자+-남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_11_남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_11_남자+-남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_12_남성.xlsx
2005
../xlsx_data/#4_result/#4_남성\#4_2005_12_남자+-남성.xlsx
================== 여기까지 : 2005 년 ==================
2006

../xlsx_data/#4_result/#4_남성\#4_2006_01_남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_01_남자+-남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_02_남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_02_남자+-남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_03_남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_03_남자+-남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_04_남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_04_남자+-남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_05_남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_05_남자+-남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_06_남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_06_남자+-남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_07_남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_07_남자+-남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_08_남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_08_남자+-남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_09_남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_09_남자+-남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_10_남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_10_남자+-남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_11_남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_11_남자+-남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_12_남성.xlsx
2006
../xlsx_data/#4_result/#4_남성\#4_2006_12_남자+-남성.xlsx
================== 여기까지 : 2006 년 ==================
2007
../xlsx_data/#4_result/#4_남성\#4_2007_01_남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_01_남자+-남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_02_남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_02_남자+-남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_03_남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_03_남자+-남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_04_남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_04_남자+-남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_05_남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_05_남자+-남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_06_남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_06_남자+-남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_07_남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_07_남자+-남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_08_남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_08_남자+-남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_09_남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_09_남자+-남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_10_남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_10_남자+-남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_11_남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_11_남자+-남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_12_남성.xlsx
2007
../xlsx_data/#4_result/#4_남성\#4_2007_12_남자+-남성.xlsx
================== 여기까지 : 2007 년 ==================
2008
../xlsx_data/#4_result/#4_남성\#4_2008_01_남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_01_남자+-남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_02_남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_02_남자+-남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_03_남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_03_남자+-남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_04_남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_04_남자+-남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_05_남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_05_남자+-남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_06_남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_06_남자+-남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_07_남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_07_남자+-남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_08_남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_08_남자+-남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_09_남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_09_남자+-남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_10_남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_10_남자+-남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_11_남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_11_남자+-남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_12_남성.xlsx
2008
../xlsx_data/#4_result/#4_남성\#4_2008_12_남자+-남성.xlsx
================== 여기까지 : 2008 년 ==================
2009
../xlsx_data/#4_result/#4_남성\#4_2009_01_남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_01_남자+-남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_02_남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_02_남자+-남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_03_남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_03_남자+-남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_04_남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_04_남자+-남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_05_남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_05_남자+-남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_06_남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_06_남자+-남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_07_남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_07_남자+-남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_08_남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_08_남자+-남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_09_남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_09_남자+-남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_10_남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_10_남자+-남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_11_남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_11_남자+-남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_12_남성.xlsx
2009
../xlsx_data/#4_result/#4_남성\#4_2009_12_남자+-남성.xlsx
================== 여기까지 : 2009 년 ==================
2010
../xlsx_data/#4_result/#4_남성\#4_2010_01_남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_01_남자+-남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_02_남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_02_남자+-남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_03_남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_03_남자+-남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_04_남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_04_남자+-남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_05_남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_05_남자+-남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_06_남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_06_남자+-남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_07_남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_07_남자+-남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_08_남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_08_남자+-남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_09_남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_09_남자+-남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_10_남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_10_남자+-남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_11_남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_11_남자+-남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_12_남성.xlsx
2010
../xlsx_data/#4_result/#4_남성\#4_2010_12_남자+-남성.xlsx
================== 여기까지 : 2010 년 ==================
2011
../xlsx_data/#4_result/#4_남성\#4_2011_01_남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_01_남자+-남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_02_남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_02_남자+-남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_03_남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_03_남자+-남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_04_남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_04_남자+-남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_05_남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_05_남자+-남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_06_남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_06_남자+-남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_07_남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_07_남자+-남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_08_남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_08_남자+-남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_09_남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_09_남자+-남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_10_남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_10_남자+-남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_11_남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_11_남자+-남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_12_남성.xlsx
2011
../xlsx_data/#4_result/#4_남성\#4_2011_12_남자+-남성.xlsx
================== 여기까지 : 2011 년 ==================
2012

../xlsx_data/#4_result/#4_남성\#4_2012_01_남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_01_남자+-남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_02_남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_02_남자+-남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_03_남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_03_남자+-남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_04_남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_04_남자+-남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_05_남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_05_남자+-남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_06_남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_06_남자+-남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_07_남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_07_남자+-남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_08_남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_08_남자+-남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_09_남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_09_남자+-남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_10_남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_10_남자+-남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_11_남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_11_남자+-남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_12_남성.xlsx
2012
../xlsx_data/#4_result/#4_남성\#4_2012_12_남자+-남성.xlsx
================== 여기까지 : 2012 년 ==================
2013
../xlsx_data/#4_result/#4_남성\#4_2013_01_남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_01_남자+-남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_02_남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_02_남자+-남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_03_남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_03_남자+-남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_04_남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_04_남자+-남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_05_남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_05_남자+-남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_06_남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_06_남자+-남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_07_남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_07_남자+-남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_08_남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_08_남자+-남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_09_남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_09_남자+-남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_10_남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_10_남자+-남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_11_남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_11_남자+-남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_12_남성.xlsx
2013
../xlsx_data/#4_result/#4_남성\#4_2013_12_남자+-남성.xlsx
================== 여기까지 : 2013 년 ==================
2014
../xlsx_data/#4_result/#4_남성\#4_2014_01_남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_01_남자+-남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_02_남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_02_남자+-남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_03_남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_03_남자+-남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_04_남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_04_남자+-남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_05_남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_05_남자+-남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_06_남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_06_남자+-남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_07_남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_07_남자+-남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_08_남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_08_남자+-남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_09_남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_09_남자+-남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_10_남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_10_남자+-남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_11_남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_11_남자+-남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_12_남성.xlsx
2014
../xlsx_data/#4_result/#4_남성\#4_2014_12_남자+-남성.xlsx
================== 여기까지 : 2014 년 ==================
2015
../xlsx_data/#4_result/#4_남성\#4_2015_01_남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_01_남자+-남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_02_남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_02_남자+-남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_03_남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_03_남자+-남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_04_남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_04_남자+-남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_05_남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_05_남자+-남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_06_남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_06_남자+-남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_07_남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_07_남자+-남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_08_남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_08_남자+-남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_09_남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_09_남자+-남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_10_남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_10_남자+-남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_11_남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_11_남자+-남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_12_남성.xlsx
2015
../xlsx_data/#4_result/#4_남성\#4_2015_12_남자+-남성.xlsx
================== 여기까지 : 2015 년 ==================
2016
../xlsx_data/#4_result/#4_남성\#4_2016_01_남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_01_남자+-남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_02_남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_02_남자+-남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_03_남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_03_남자+-남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_04_남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_04_남자+-남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_05_남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_05_남자+-남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_06_남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_06_남자+-남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_07_남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_07_남자+-남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_08_남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_08_남자+-남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_09_남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_09_남자+-남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_10_남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_10_남자+-남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_11_남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_11_남자+-남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_12_남성.xlsx
2016
../xlsx_data/#4_result/#4_남성\#4_2016_12_남자+-남성.xlsx
================== 여기까지 : 2016 년 ==================
2017
../xlsx_data/#4_result/#4_남성\#4_2017_01_남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_01_남자+-남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_02_남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_02_남자+-남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_03_남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_03_남자+-남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_04_남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_04_남자+-남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_05_남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_05_남자+-남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_06_남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_06_남자+-남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_07_남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_07_남자+-남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_08_남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_08_남자+-남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_09_남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_09_남자+-남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_10_남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_10_남자+-남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_11_남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_11_남자+-남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_12_남성.xlsx
2017
../xlsx_data/#4_result/#4_남성\#4_2017_12_남자+-남성.xlsx
================== 여기까지 : 2017 년 ==================
2018

../xlsx_data/#4_result/#4_남성\#4_2018_01_남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_01_남자+-남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_02_남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_02_남자+-남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_03_남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_03_남자+-남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_04_남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_04_남자+-남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_05_남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_05_남자+-남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_06_남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_06_남자+-남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_07_남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_07_남자+-남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_08_남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_08_남자+-남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_09_남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_09_남자+-남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_10_남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_10_남자+-남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_11_남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_11_남자+-남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_12_남성.xlsx
2018
../xlsx_data/#4_result/#4_남성\#4_2018_12_남자+-남성.xlsx
================== 여기까지 : 2018 년 ==================
2019
../xlsx_data/#4_result/#4_남성\#4_2019_01_남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_01_남자+-남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_02_남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_02_남자+-남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_03_남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_03_남자+-남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_04_남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_04_남자+-남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_05_남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_05_남자+-남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_06_남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_06_남자+-남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_07_남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_07_남자+-남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_08_남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_08_남자+-남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_09_남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_09_남자+-남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_10_남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_10_남자+-남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_11_남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_11_남자+-남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_12_남성.xlsx
2019
../xlsx_data/#4_result/#4_남성\#4_2019_12_남자+-남성.xlsx
================== 여기까지 : 2019 년 ==================

In [6]:
mdf_year

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,3073,4701,7638,12174,22315,30483,39120,48442,54155,78057,72594,87253,105274,142964,188902,242221,202778,181509,207519,204009
1,2700,4160,6502,8357,16693,30414,44588,51422,58899,100022,102248,128534,158869,212762,292607,326000,231877,204667,205591,179426

In [104]:
chart = pygal.Line()
chart.x_labels = mdf_year.columns
chart.add('긍정', mdf_year.loc[0])
chart.add('부정', mdf_year.loc[1])
chart.render_to_file('m_sentiment_line.svg')
mdf_year.to_csv('sent_m_count.csv')

In [52]:
from collections import Counter
df_name = glob.glob('../xlsx_data/#4_result/#4_남성/')
cnt = 0
sum = 0
for i, d in enumerate(df_name):
        for f in glob.glob(d+"/*.xlsx"):
            year = f[32:36]
            if year == '2019':
                df = pd.read_excel(f)
                print('길이' , len(df))
                sum+= len(df)
                print(f)
                try:
                    temp = df.sentiment.value_counts().sort_index()
                    
                    mdf_year[year] += temp                    
                except:
                    print('empty file')
                    pass
                if cnt%24 == 0:
                    print('================== 여기까지 :', year, '년 ==================')

길이 14288
../xlsx_data/#4_result/#4_남성\#4_2019_01_남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 22886
../xlsx_data/#4_result/#4_남성\#4_2019_01_남자+-남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 12895
../xlsx_data/#4_result/#4_남성\#4_2019_02_남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 16563
../xlsx_data/#4_result/#4_남성\#4_2019_02_남자+-남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 15035
../xlsx_data/#4_result/#4_남성\#4_2019_03_남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 14875
../xlsx_data/#4_result/#4_남성\#4_2019_03_남자+-남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 15001
../xlsx_data/#4_result/#4_남성\#4_2019_04_남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 15080
../xlsx_data/#4_result/#4_남성\#4_2019_04_남자+-남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 16112
../xlsx_data/#4_result/#4_남성\#4_2019_05_남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 17983
../xlsx_data/#4_result/#4_남성\#4_2019_05_남자+-남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 16279
../xlsx_data/#4_result/#4_남성\#4_2019_06_남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 16670
../xlsx_data/#4_result/#4_남성\#4_2019_06_남자+-남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 16700
../xlsx_data/#4_result/#4_남성\#4_2019_07_남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 16566
../xlsx_data/#4_result/#4_남성\#4_2019_07_남자+-남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 15432
../xlsx_data/#4_result/#4_남성\#4_2019_08_남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 15078
../xlsx_data/#4_result/#4_남성\#4_2019_08_남자+-남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 14926
../xlsx_data/#4_result/#4_남성\#4_2019_09_남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 15852
../xlsx_data/#4_result/#4_남성\#4_2019_09_남자+-남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 15408
../xlsx_data/#4_result/#4_남성\#4_2019_10_남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 17933
../xlsx_data/#4_result/#4_남성\#4_2019_10_남자+-남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 15108
../xlsx_data/#4_result/#4_남성\#4_2019_11_남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 17317
../xlsx_data/#4_result/#4_남성\#4_2019_11_남자+-남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 14483
../xlsx_data/#4_result/#4_남성\#4_2019_12_남성.xlsx
================== 여기까지 : 2019 년 ==================
길이 14965
../xlsx_data/#4_result/#4_남성\#4_2019_12_남자+-남성.xlsx
================== 여기까지 : 2019 년 ==================

In [53]:
sum

383435

In [56]:
from collections import Counter
df_name = glob.glob('../xlsx_data/#4_result/#4_남성/')
cnt = 0
sum19 = 0
sum15 = 0
for i, d in enumerate(df_name):
        for f in glob.glob(d+"/*.xlsx"):
            year = f[32:36]
            if year == '2019':
                print(f)
                df = pd.read_excel(f)
                sum19 += len(df)
            if year == '2015':
                print(f)
                df = pd.read_excel(f)
                sum15 += len(df)

../xlsx_data/#4_result/#4_남성\#4_2015_01_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_01_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_02_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_02_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_03_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_03_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_04_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_04_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_05_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_05_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_06_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_06_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_07_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_07_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_08_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_08_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_09_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_09_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_10_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_10_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_11_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_11_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_12_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2015_12_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_01_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_01_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_02_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_02_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_03_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_03_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_04_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_04_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_05_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_05_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_06_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_06_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_07_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_07_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_08_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_08_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_09_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_09_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_10_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_10_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_11_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_11_남자+-남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_12_남성.xlsx
../xlsx_data/#4_result/#4_남성\#4_2019_12_남자+-남성.xlsx

In [57]:
print(sum15, sum19)

568221 383435

## 비율로 그리기

In [66]:
count_list = pd.DataFrame(0, index = ['cnt'],columns=list(map(str,range(2000,2020))))
count_list

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
cnt,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [71]:
from collections import Counter
df_name = glob.glob('../xlsx_data/#4_result/#4_남성/')
cnt = 0

for i, d in enumerate(df_name):
        for f in glob.glob(d+"/*.xlsx"):
            year = f[32:36]
            print(year)
            df = pd.read_excel(f)
            count_list[year] += len(df)

In [74]:
mcount_list = count_list

In [75]:
mcount_list.to_csv('mtotal_count.csv')

In [84]:
wcount_list = pd.DataFrame(0, index = ['cnt'],columns=list(map(str,range(2000,2020))))
wcount_list

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
cnt,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [77]:
from collections import Counter
df_name = glob.glob('../xlsx_data/#4_result/#4_여성/')
cnt = 0

for i, d in enumerate(df_name):
        for f in glob.glob(d+"/*.xlsx"):
            year = f[32:36]
            df = pd.read_excel(f)
            wcount_list[year] += len(df)

In [80]:
wcount_list

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
cnt,11961,17730,29389,39552,74445,98113,134883,177801,201260,274459,273031,315978,360880,497113,651696,810230,657997,601069,646543,608797

In [81]:
wcount_list.to_csv('wtotal_count.csv')

In [85]:
from collections import Counter
df_name = glob.glob('../xlsx_data/#4_result/#4_여성/')
cnt = 0

for i, d in enumerate(df_name):
        for f in glob.glob(d+"/*.xlsx"):
            year = f[32:36]
            print(year)
            df = pd.read_excel(f)
            wcount_list[year] += len(df)

2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2002
2002
2002
2002
2002
2002
2002

KeyboardInterrupt:

In [86]:
wcount_list

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
cnt,11961,17730,5057,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [87]:
from collections import Counter
df_name = glob.glob('../xlsx_data/#4_result/#4_여성/')
cnt = 0
wdf_year = pd.DataFrame(0, index=range(0,2),columns=list(map(str,range(2000,2020))))
for i, d in enumerate(df_name):
        for f in glob.glob(d+"/*.xlsx"):
            year = f[32:36]
            print(year)
            cnt += 1
            df = pd.read_excel(f)
            print(f)
            try:
                temp = df.sentiment.value_counts().sort_index()
                wdf_year[year] += temp                    
            except:
                print('empty file')
                pass
            if cnt%24 == 0:
                print('================== 여기까지 :', year, '년 ==================')

2000
../xlsx_data/#4_result/#4_여성\#4_2000_01_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_01_여자+-여성.xlsx
empty file
2000
../xlsx_data/#4_result/#4_여성\#4_2000_02_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_02_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_03_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_03_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_04_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_04_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_05_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_05_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_06_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_06_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_07_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_07_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_08_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_08_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_09_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_09_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_10_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_10_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_11_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_11_여자+-여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_12_여성.xlsx
2000
../xlsx_data/#4_result/#4_여성\#4_2000_12_여자+-여성.xlsx
================== 여기까지 : 2000 년 ==================
2001
../xlsx_data/#4_result/#4_여성\#4_2001_01_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_01_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_02_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_02_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_03_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_03_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_04_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_04_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_05_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_05_여자+-여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_06_여성.xlsx
2001
../xlsx_data/#4_result/#4_여성\#4_2001_06_여자+-여성.xlsx
2001

KeyboardInterrupt:

In [88]:
wdf_year

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,6219,4513,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,5742,4711,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## 여자 남자 긍부정 전체 카운트

- sent_w_count.csv : 여자 긍부정 카운트
- sent_m_count.csv : 남자 긍부정 카운트

In [5]:
wcount = pd.read_csv('sent_w_count.csv', index_col=0)
mcount = pd.read_csv('sent_m_count.csv', index_col=0)

In [18]:
wcount.loc[0].sum()

3072437

In [15]:
chart = pygal.Pie()
chart.title = '긍부정 분포'
chart.add('긍정' , wcount.loc[0].sum())
chart.add('부정' , wcount.loc[1].sum())
chart.render()

chart.render_to_file('wsenttotal.svg')

In [14]:
chart = pygal.Pie()
chart.title = '긍부정 분포'
chart.add('긍정' , mcount.loc[0].sum())
chart.add('부정' , mcount.loc[1].sum())
chart.render()

chart.render_to_file('msenttotal.svg')

In [19]:
mcount

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,3073,4701,7638,12174,22315,30483,39120,48442,54155,78057,72594,87253,105274,142964,188902,242221,202778,181509,207519,204009
1,2700,4160,6502,8357,16693,30414,44588,51422,58899,100022,102248,128534,158869,212762,292607,326000,231877,204667,205591,179426

In [20]:
wcount

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,6219,8852,16020,22677,42207,50262,67439,89563,98410,124304,118355,132364,164125,218280,276896,364106,325017,291384,328168,327789
1,5742,8878,13369,16875,32238,47851,67444,88238,102850,150155,154676,183614,196755,278833,374800,446124,332980,309685,318375,281008